workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: 'hey'
      groups:
        - test
        - test2
    scripts:
      - echo $FOO
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
