workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: 'hey'
      groups:
        - app_group
        - same_group
        - team_group
        - team_group2
        - app_group2
    scripts:
      - echo $FOO
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
