workflows:
  cat:
    name: def
    max_build_duration: 5
    instance_type: linux_x2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.id
      flutter:
        version: fvm
        flavor: dev
    scripts:
      - echo "hi"
