workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        CM_CLONE_DEPTH: 1
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    when:
      condition: event.action != "ready_for_review"
    scripts:
      - echo 'hi'
    artifacts:
      - "*.snap"
      - build/windows/**/*.msix
      - flutter_drive.log
