workflows:
  default-workflow:
    name: def
    instance_type: mac_mini_m1
    environment:
      xcode: 14
    max_build_duration: 60
    scripts:
      - xcrun --sdk macosx --show-sdk-path
      - echo $SDKROOT
      - sleep 180
