workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 13.3
    max_build_duration: 60
    labels:
      - cat
      - Dog
    scripts:
      - echo 'hi'
    artifacts:
      - "*.snap"
      - build/windows/**/*.msix
      - flutter_drive.log
