workflows:
  my-workflow:
    name: My new test workflow
    instance_type: mac_pro
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - pull_request
    scripts:
      - name: Skip build
        script: curl -H "Content-Type: application/json" -H "x-auth-token: <API Token>" --request POST https://api.codemagic.io/builds/$FCI_BUILD_ID/cancel
        when:
          changeset:
            includes:
              - 'app/**'
