workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: 'hey'
      groups:
        - same_group
        - team_group
        - app_group
    scripts:
      - echo $SECRET
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
