workflows:
  my-workflow:
    instance_type: linux
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - echo $JAVA_HOME
      - sudo update-java-alternatives -s $JAVA_HOME --jre-headless
      - sleep 20
