workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: Encrypted(Z0FBQUFBQmhCX0RuYU5CdWpjWTlvS0ZOYkp6akVFeDd5NUk1WmpzNU10MGJMekJTTVRYMVBuZnMxS1hxWTZYSGFMODR1LWY3ZG1KcTJIV2hZMUh5WFlyZEMycFQ1aGpSdVE9PQ==)'
    scripts:
      - echo $FOO
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
