workflows:
  first:
    name: prank
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    environment:
      cocoapods: 1.10.1
    scripts:
      - echo 'hello'
      - sleep 20
      - echo $RBENV_VERSION
      - rbenv version

