workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: Encrypted(Z0FBQUFBQmhCX0hzcmdxelRFaGo3X1RCcmhXLUp5Vi1WZmtDZUR5cXVHVENzU19ySkh4aUdQbS1HSVdJXzBuelM2RUhzSmlVbTB4ajFIUXNqX25URmdQUTlQWTh3S1FnR1E9PQ==)
    scripts:
      - echo $FOO
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
