workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: 'hey'
      groups:
        - magic
        - llama
    scripts:
      - echo $TEST_STUFF
      - echo $JAVA_HOME
      - sleep 100
