workflows:
  my-workflow:
    name: My new test workflow
    instance_type: mac_pro
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - pull_request
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
        - pattern: "main"
          include: false
          source: false
        - pattern: "main"
          include: false
          source: true
    scripts:
      - echo 'hi'
