workflows:
  cat:
    environment:
      xcode: 14
    name: def
    max_build_duration: 60
    triggering:
      events:                       # List the events that trigger builds
        - pull_request
      branch_patterns:              # Include or exclude watched branches
        - pattern: '*'
          include: true
          source: true
    scripts:
      - |
        set -e
        # weird
        echo "weird"
