workflows:
  first:
    name: prank
    environment:
      node: 14.15.5
      ndk: r19c
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - echo 'hello'

