workflows:
  first:
    name: prank
    environment:
      vars:
        RBENV_VERSION: 2.5.1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - echo 'hello'

