workflows:
  cat:
    name: def
    max_build_duration: 2
    triggering:
      events:                       # List the events that trigger builds
        - push
      branch_patterns:              # Include or exclude watched branches
        - pattern: '*'
          include: true
          source: true
    scripts:
      - echo "hi"
