workflows:
  my-workflow:
    publishing:
      scripts:
        - name: Check for APK
          script: |
            apkPath=$(find build -name "*.apk" | head -1)
            if [[ -z ${apkPath} ]]
            then
              echo "No .apk were found"
            else
              echo "Publishing .apk artifacts"
            fi      
