workflows:
  my-workflow:
    name: first
    environment:
      vars:
        TOKEN: 'catcatcat'
        FIREBASE_ANDROID_ID: 'catcatcat'
    scripts:
      - echo $JAVA_HOME
      - echo $KASS
      - echo $TASS
      - echo $WHY
    artifacts:
      - testing/*.aab
    publishing:
      firebase:
        firebase_token: $TOKEN
        android:
          artifact_type: apk
          app_id: $FIREBASE_ANDROID_ID
          groups:
            - magicGroup
