workflows:
  first:
    name: prank
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - echo 'hello'

