workflows:
  my-workflow:
    name: first
    environment:
      groups:
        - esimene
      vars:
        WHY: 'catcatcat'
    scripts:
      - echo $JAVA_HOME
      - echo $KASS
      - echo $TASS
      - echo $WHY
