workflows:
  first:
    name: first
    environment:
      node: 14.15.5
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - echo 'hello'
  second:
    name: second
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - echo 'hello'
  third:
    name: third
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - echo 'hello'

