workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: 'hey'
      groups:
        - same_group
        - BAM
    scripts:
      - echo $SECRET
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
