workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini
    max_build_duration: 60
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    when:
      condition: not event.action.ready_for_review
    scripts:
      - flutter packages pub get
    artifacts:
      - "*.snap"
      - build/windows/**/*.msix
      - flutter_drive.log
