workflows:
  my-workflow:
    name: first
    environment:
      node: v16.11.1
      vars:
        TOKEN: 'catcatcat'
        FIREBASE_ANDROID_ID: 'catcatcat'
        BETTER: 'dong'
      groups:
        - esimene
    scripts:
      - sleep 1000
      - echo $JAVA_HOME
      - echo $KASS
      - echo $TASS
      - echo $WHY
    artifacts:
      - testing/*.aab
    publishing:
      google_play: # For Android app
        credentials: $BETTER # Contents of the JSON key file for Google Play service account saved as a secure environment variable
        track: alpha # Name of the track: internal, alpha, beta, production, internal app sharing, or your custom track name
        submit_as_draft: True
