workflows:
  default-workflow:
    instance_type: mac_pro
    environment:
      xcode: 12.5
    name: def
    max_build_duration: 60
    scripts:
      - |
        set -e
        # weird
        echo "weird"
