workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: Encrypted(Z0FBQUFBQmhCX0pNbXVvNjU0ZjBLMmJkTkNuZ2lpdzljYVhoNDFPSFc5R3I4TzVkQy1FVGp0TkdNRUgxNzRwUGpvMG9oRnZua0Q3NHA2b29CcThjVHZnZ0V1cFZMOTR3M0E9PQ==)
    scripts:
      - echo $FOO
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
