workflows:
  my-workflow:
    name: My new test workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - $CM_BUILD_DIR/meow_folder
    scripts:
      - sleep 30
