workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: 'hey'
      groups:
        - group2
        - group1
    scripts:
      - echo $SECRET
      - echo $MAGIC
      - echo $TEST_STUFF
      - sleep 100
