
workflows:
  ios:
    name: iOS
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: 7d812fe2-8abd-47ca-9d27-3ed7e62d7b6d
        APP_STORE_CONNECT_KEY_IDENTIFIER: 4M66TCH2ZC
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmZrV3NlNzE0Q05IR0pVSDVOSVRUbnN2c2FabHJwanBMbVF4N0toRUxtZWdESUg1YXZPaC0xV1luMXV6YmVnSHNzZDZTTkxfendaUXZCMHVkZXRJWVhVTk01X2hnd0Q3bmtxOWFNRlhvUTAyWjJBd0FnMUhLNUY4Y2N6R080RlV1X2hwMzFyRU51OGRUWEdNYnR6eGtITzJWcnJzdkgxSnNwcHpOVUpWRFd3LXNMangxVTZPYzVycWh1QmZNS1lsN1ZFbDdTU0JuY05LbjRoM1h1dWVPMEFUWmFwdDhyU0E4RWt6NmRsLUFvNWtiUnFaNWJjeFJCZ3JMNXBJenI0OXJWQXV3ZklNZWxLUU1td3lrTUx6dlhfYUhWR2lFcVVoek5BQjE4UGpDWmNpMXJwakoyU2FzX214X29mVGwxb1lYWllWTEVYSmhKUjcxR0tsOC1meExkY3NybHFyaDU5QXlGVEQ2ODdtbW41VkJqWnh2V1RKVmNSSmtoOFptWVI4TFlsbUFmZDc3emZjNTJ4aHllNHQybnZnNnV0OUg4Qkl0UHBBeG53YVMzNTRld1dsaz0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmZrV3NleEstYm91UUFBeXFRaEFGNzdRZE9EUkJvOUc3c1lneVZJaTJTbEx6TjZtVk9iRkhWR3hFajJRd2dyRzNuOEk5V3JHS3g1ZnpuMzAwN3NYcHI5VHJfdTJheXd0UUdQYS00WHZxaFVUVXpqTENGc0g2cHBvSG9ycEIwWk82M3c5WFAyWjJxTTdYaW8zOXBESGNxajhBWkRoMUpnZks2TE95UFhUNmRLbFR6S0xUdXpBaTVFalBoMW9GU1hNeXdNLVItSWtSRkFON3dpd0RfOHAtaDY3STJNVk01N21rTVpnUEJiYmtRcDcwTEQ0V19UOElTM0Y1c2JEam9tMXc3Z1E0dXdkazlmbHkzTE9jUFJYdzVvZVVNS0xZTTI1U1J2b01WUkxJWGNwakxGZWhUSXhuNEo2VEl0T1R6QkJLNm5HaE9jTTI1eGd6M3lOMGhLcFotX0k1UkZtbmt4ZV9PQ2pHZXV6aFZUYi1KSVNMOVp3T2FUUDVwUWxlQUczMjh3WWpEUHVPVDFxWmx2THpwNDhYVXZzSmh6VkN0cnN3a05MbjBQdXExRTJUdV9CdnQ5aEEwcUhOSElOclQzUDkyYk5zdlhZcE9QVWtCLUZCc0prelJ1SFFRWlo5eWNoUVF6N3JWeU9qc0NxTEtUcDVtUl9YcEVMbURZa3IyUEgzYUJwd3dsYXBXUmMyWWFUTjkyN25YNTVxN2hfNGVuZ3RuTTNPMWZ5Xzhpdl8wQXpEMTU3Q29VTzh5VTBfTGMwVTc4REtWRktpRE9EZ2pBTVlfdVpuVzFoUlJ5NS1GQk9vbEc5bWpXSThkU0JQMEpQTHpfdkg4U0RiTTlraDd2RUlCSW9Mc0V1WFRabi1QaXI5VnBlRF9xOGgyV25SV2ZYaEtzczYzOVJnZFFRNDJuLTZwd2p4NnpJS0ljRG1Odk56YmI5NWxBZVZycTVZTjV6eXNDMC1uelNiTWlrTVFJbW9kYklhaTJsUEFHMWVSdzltX0JXSVdjUFlxbDF0My1oT1d2elplVm9Pc0tzcGVmdFpLT0FFWUgwYy1pYzhxSElBTlFneG91MDZ1TGJKU2pQTEVTaGhjQVlIckx3Nlp1R1F2VmpoeDVGLXZmbGM5anJRNENhX2xleVV3YzRwQmwyMnE2VEQxTUdLODVGS3hwN1FNRVFtdTdjeVJCaXU2bHFqSmdSMVdPdnVRRW9CdHJ5MS1IX2REaG9NbjlUTFRteE1lb0RJaGRLTVlndTlGaGp2Yk53eldCN0YzX0tQRzdFU1d6WUlBcmpXQkotU0xyWFdLY3o1TjdXaVVPbEpmbTQtZVV4YmQxbEVFWG1RMFlDU1d4LXJJaUp1VFk2b3hnRmIxMkhRTmpyQk9lUTNmeXdLUC1XMU1uTG00QXdUZWt1VHVMTE5HSTJaaWNxNEo0QzZBalBFWVloekpVc1RsVGt5a3YwMmozTHlfTGh3VExlamJVeV9HQU1QMDY3M2gwX0hWUTRXOFRBODB3R0ZDbFBtLUxxVEQ2OHEza1piV2VXWE9mV0NJYllkWjRaRFhmalA4aTM2WEsycmU3OHFuUk5YWHZra29hbXZOV0tzZHBWd3d2dUItZGUzMjBqa2VST1N1RFlSV1dvbnZOcmRsUzFkcGlsbkU2TzdjT0lZMFN4bFZrWVFXRFoxZ0k4THJVRzNwcTNpMi0yTU0yOHVEaFFvSXIxM3RsSFJDcGVNZkp4Ujh1dkxESTF6MHlXVkhkWG5VXzdzaEVMMTdLTEIwb1hiLVJ6d0trZTNNWmQwbUF3bWdISEJyanRJbW5hcjlvYUZOUzVqQzZ1X1lWU1JJS2tQZmRZVXpYcE5hVUpnMmlva0E2QnNxUDl4WXBKTWF3WHJyd0pVQlB4dUxjYWZ1emVLYzBvbUZVOFk0TkNpOEhEd2cyMTZlSk9meWJpb2FyeGs1aWE5T1VTMXpVU3pnYjNTT0QtRlZRSmxrOEpvT29XdkQtU0NVSEhuTE5QUWliX1ZZMkYxWExJTEhwVGZWenpxc0dFYTdDWVd4Y3lvTzF2ZEtDZXJubjZQNmFWc2FHVWUwUVhHQlNxQ1JRRVlFcVpHd3pHckpzeDFaNnVhUFZ2aUVveURBel9FTzBhUy1iWTJ2S29ndC1XR1JYLWVXRGlRdHFyVlNaNjNzM1J6RFVwYUNRamY3V1h3OGcxNDVOSzVlZldNOGs0UTVIOTRHVDhINnJsU0ZvQnRuRlFtUXlmbW4xWkxrOGk5YmRqUjBMWnMxTlBVUkQ3ejVpUGxqV0pTUjNESHFKVnNMWUx3YVcwM3R6bm5fcjlTNzlWT29RY2lvclN0NklPNXFvZVZsREh4ZjlqbmhQQlJIdTZibnZRbktVRXg2bkJUSzZIRFZtR0I3SXpTWk84eTFON1h5dThENzFIWm45V2s4UUNSOXVkUjRxdWoxamFxdUk5cGtWX0pfNXdDVkk3a04tMmdleUxLcEpoNEhodEtLRkUtdGdQeXhpT3FvRzUtc1k5c18zZEx1MzF0N1pCNnRxU2lKUDdwMW1XQ29fazc2Q3ZQQjF3eWZWbEJ5cGxyM3FuWGlRbTliNkZtRl9tNDRVd0luZGJ0bXZScEh4dDNjaTMxSl93OVhFRWY5OXJSa2xzaHBJY1dSVEdDSmRWc1YzcmhlZVpWOGQzS3RPMjFueHdPQ3pfM1BCSWlRZ3NRN2diSDZZajZOY3oyemVjYUkwQ1VXbUU0TmstejQwaVFVVWl1alRhVWtXNksyWXBzTFhoVFpJdi1PbFNiR0pISGRNQ0R2S3d4M3RJMWJrVlUyN2Jsc3NoXzRHSWEyMTZtTHFLMWdmal9Ma0thTkFzbGZTdjluZ2cyTGFTZjMxSk5KVkVQZkFiWlFqVEJiZU9NUUVzMlpOMmVwNllMbGFpT1FOYTR3cHYxWWtWVjQydWpXOWZjZ3hhYm4yeDRwUkRKSF9kWjVKOGw5TUV0ZGRFZ0l2S0FZSVpVNGtIZlZHUUVuSW1ETmRDUWhrektQS0xDUHFfX09YWkV1LUwtQ2tmanVvaXE1UXMycjhqZEpjOGxuRmpFTDh6dFNDb3Ff)
        XCODE_WORKSPACE: yamlmanualdevelopment.xcworkspace
        XCODE_SCHEME: yamlmanualdevelopment
        DISCORD_HOOK: https://discordapp.com/api/webhooks/769114802114789406/vKmeUbq8VcWfas0MAMDtA0c5Ma_p5Qx0QC_kInemW03MzA9ScOGHtbqHo4OZ3Zfji66u
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "com.codemagic.yamlmanualdevelopment" --type IOS_APP_DEVELOPMENT --create
      - keychain add-certificates
      - xcode-project use-profiles
      - xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      - name: Webhook notification
        script: |
            export PROJECT_URL=https://codemagic.io/app/${FCI_PROJECT_ID}
            payload(){
              echo '{
                  "content": "Welcome to <:discohook:735474274458140705>Discohook, a free message and embed builder for Discord!\nThere's additional info in the embeds below, or you can use the *Clear all* button in the editor to start making embeds.\nHave questions? Discohook has a support server at <https://discohook.org/discord>.",
                  "embeds": [
                    {
                      "title": "What's all this?",
                      "description": "Discohook is a free tool that allows you to build Discord messages and embeds for use in your server.\n\nDiscohook sends messages using *webhooks*, an API feature that allows third-party services to *blindly* send messages into text channels. While webhooks can send messages, they cannot respond to user interactions such as messages.",
                      "color": 7506394
                    },
                    {
                      "title": "Text formatting how-tos",
                      "description": "There are a few basic styles you can take advantage of:\n*Italics*, by surrounding text in asterisks (\\*);\n**Bold**, by surrounding text in double asterisks (\\*\\*);\n__Underline__, by using double underscores (\\_\\_);\n~~Strikethrough~~, by using double tildes (\\~\\~);\n`Code`, by using backticks (\\`).",
                      "color": 4437377,
                      "fields": [
                        {
                          "name": "Advanced formatting",
                          "value": "Beyond these basic styles, you can also start a blockquote with a right-pointing angle bracket (>):\n> Hello.\nOr mark sensitive content behind a spoiler using two vertical bars (\\||):\n||This is hidden until clicked||"
                        },
                        {
                          "name": "Using server emoji",
                          "value": "While default emoji work like you would expect them to, server emotes are a bit more complicated.\n\nTo send a server emoji with a webhook, you must use a specific formatting code to do so. To find it, send that emoji in your server, but put a backslash (\\\\) in front of it.\n\nFor example: sending `\\:my_emoji:` would send `<:my_emoji:12345>` into chat. If you copy the output into Discohook, the emoji will show up properly."
                        },
                        {
                          "name": "Pinging users and roles, linking to channels",
                          "value": "First of all, you must have enabled developer mode in Discord's settings. To do so, open Discord settings and navigate to Appearance. There will be a Developer Mode toggle under the Advanced section, which you must enable.\n\nHaving developer mode enabled, you can now right-click your target to copy their ID. Keep in mind that for users, you must right click their *avatar*, not the message.\n\nTo mention them, you have to use Discord's mention syntax:\n`<@!user_id>`, `<@&role_id>`, or `<#channel_id>`. If done correctly, they will appear as <@!143419667677970434> in the preview."
                        }
                      ]
                    },
                    {
                      "title": "Additional magic",
                      "color": 16426522,
                      "fields": [
                        {
                          "name": "Image galleries",
                          "value": "With some special magic, you can have up to 4 images in a single embed. This feature is exclusive to webhooks, so don't expect to make it work on a traditional bot.\n\nAll you need is to give your embed a URL and click on the \"Edit images\" button inside any embed to get started."
                        },
                        {
                          "name": "Backups",
                          "value": "Not only can Discohook send messages, but Discohook can also save them for later use. For when your message wasn't quite right.\nFor convenience, backups also contain the webhook URL.\n\nBackups will not be sent to the Discohook, and will always be stored offline. If you clear your browsing data, your backups will be lost *forever*!\n\nIf you want to keep your backups somewhere else, you can export backups to get a saved copy. Do keep in mind that they also include the stored webhook URL, so don't share it with anyone you don't trust."
                        }
                      ]
                    },
                    {
                      "title": "Legal things",
                      "description": "To make Discohook as helpful as it can be, we use some assets derived from Discord's application. Discohook has no affiliation with Discord in any way, shape, or form.\n\nThe source code to this app is [available on GitHub](https://github.com/discohook/discohook) licensed under the GNU Affero General Public License v3.0.\nIf you need to contact me, you can join the [support server](https://discohook.org/discord), or send an email to \"hello\" at discohook.org.",
                      "color": 15746887
                    }
                  ]
              }'
            }
            curl $DISCORD_HOOK \
              --header "Content-Type: application/json" \
              --request POST \
              --data "$(payload)"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
