workflows:
  my-workflow:
    environment:
      vars:
        TEST_STUFF: show
      groups:
        - team
        - app
        - same
    scripts:
      - echo $LAHE
      - echo $LAHE2
      - echo $LAHE3
      - sleep 100
