workflows:
    first:
        name: first
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
     second:
        name: second
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
     third:
        name: third
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
