version: 2.1

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - android
            - ios

jobs:
  run-tests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
